export const allCapabilities = [
    'Cap1',
    'Cap2',
    'Cap3',
    'Cap4',
    'Cap5',
    'Cap6',
    'Cap7',
    'Cap8',
    'Cap9',
    'Cap10',
  ];
  
export const rawTableData = [
    {
      Capability: 'Cap1',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, 3DS',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap2',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM, Microservices, APIGEE, Salesforce, SAP ERP, SAP S/4HANA, ETL, EPM',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap3',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, Informatica ETL, Elastic',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap4',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, Informatica ETL, Elastic',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$11,000',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap5',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, Informatica ETL, Elastic, SAP S/4HANA',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap6',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, Informatica ETL, Elastic, EPM',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap7',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, Informatica ETL, Azure, Elastic',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap8',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Azure',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap9',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, SAP S/4HANA',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
    {
      Capability: 'Cap10',
      Type: 'Onboarding',
      'Sub-Total': '$0',
      'Technology Stack': 'AEM/React, Microservices, APIGEE, Salesforce, Informatica ETL, Elastic',
      AEM: '$0',
      SFDC: '$0',
      Apigee: '$0',
      PIF: '$0',
      'Informatica ETL': '$0',
      Microservices: '$0',
      'SAP ERP': '$0',
      'SAP HANA': '$0',
      eDAM: '$0',
      Azure: '$0',
      PIM: '$0',
      Total: '$0',
    },
  ];
  
  export const headerColumns = [
    'Capability',
    'Type',
    'Sub-Total',
    'Technology Stack',
    'AEM',
    'SFDC',
    'Apigee',
    'PIF',
    'Informatica ETL',
    'Microservices',
    'SAP ERP',
    'SAP HANA',
    'eDAM',
    'Azure',
    'PIM',
    'Total',
  ];